### ISSUE TITLE
Chuc nang khoa va mo khoa tai khoan

### ISSUE THREAD

**Issue by AnhTuyet1992003** [chanz40000/DoAnTTLTWeb#20]
Đã sửa danh sách hiển thị của user, sửa userDAO để hiển thị danh sách riêng của user, admin, tài khoản user bị khóa, cung cấp cho admin chức năng khóa và mở khóa tài khoản của user

**Comment by Tintwentyseven** [comment]
Sửa danh sách hiển thị của user là chỉ sửa giao diện đúng ko ?

**Comment by AnhTuyet1992003** [comment]
là chỉ hiển thị user có role là user thôi còn admin thì hiện bên cái danh sách admin, sửa database hiển thị theo user có role là 1 à
